### ISSUE TITLE
source.py doesnt represent github repo

### ISSUE THREAD

**Issue by RealSoerensen** [VarunBanka/yt_downloader#1]
Hello,
I saw your repo and was interested in the project.
I looked through source.py and was a bit confused.
The file you have uploaded to this repo is a password generator.
Hope you can get it fixed and upload the correct file.
Regards!

**Comment by VarunBanka** [comment]
> Hello, I saw your repo and was interested in the project. I looked through source.py and was a bit confused. The file you have uploaded to this repo is a password generator. Hope you can get it fixed and upload the correct file. Regards!
ohh, my bad, thanks for informing me, i will fix it soon

**Comment by VarunBanka** [comment]
> Hello, I saw your repo and was interested in the project. I looked through source.py and was a bit confused. The file you have uploaded to this repo is a password generator. Hope you can get it fixed and upload the correct file. Regards!

okay, my bad, thnaks for informing, ill fix it soon

**Comment by VarunBanka** [comment]
> Hello, I saw your repo and was interested in the project. I looked through source.py and was a bit confused. The file you have uploaded to this repo is a password generator. Hope you can get it fixed and upload the correct file. Regards!


fixed
